language: python

python: 
  - 3.6
  - 2.7

env:
  - TOXENV=lint,build-py36,py36
  - TOXENV=lint,build-py27,py27

matrix:
  exclude:
    - python: 3.6
      env: TOXENV=lint,build-py27,py27

    - python: 2.7
      env: TOXENV=lint,build-py36,py36

install:
  - pip install tox

script:
  - tox


jobs:
  include:
    - stage: deploy
      script: echo "Deploying to PyPI..."
      deploy:
        provider: pypi
        user: freelancer
        password: ${PYPI_PASSWORD}
        on:
          tags: true

# To run TravisCI and build locally:
# 1. Download Docker
# 2. Run a docker container with a travisci/ci-python image.
# 3. Switch to the travis user using: `su - travis`
# 4. Install the wwtd(What Will Travis Do) gem.
#    it will run your project's .travis.yml for you.
#    ensure that tox, python3 and python2.7 are installed.
# 5. Run `pyenv shell 3.6 2.7` to prepare the needed venvs.
# 6. Run `wwwtd -u install -u language` to force travis to use your settings.
# 7. If your builds succeed, then you are good to go. :)
